### ISSUE TITLE
h5py support for additional filters

### ISSUE THREAD

**Issue by aragilar** [silx-kit/hdf5plugin#14]
Hi hdf5plugin developers

I came across this project via https://github.com/h5py/h5py/issues/923, I wonder if you guys would be interested contributing support in h5py for detecting the installation of hdf5 filters via (something like) entry points, which would mean that users wouldn't have to worry about import order?

**Comment by vasole** [comment]
Hi

Concerning the entry points, sure, we can collaborate. However I think the cleanest solution would be to try to use the hdf5filterplugin (or any other way to provide the filters) only when one has already made the diagnostic the filter is missing. The problem the HDF5 function that one should use is buggy:

https://github.com/h5py/h5py/issues/843

One limitation of our filters is that in order to fix the bitshuffle filter we had to get rid of the writing part. So, we have to be sure we sit at the end of the filter path in order to give the user the opportunity to use his own local installation.

**Comment by vasole** [comment]
The HDF group tells me that HDF5 1.8.19 introduced the possibility to append directories to the path:

https://support.hdfgroup.org/HDF5/doc1.8/RM/RM_H5PL.html#Plugin-Append

I still have to get the information about that option being available on 1.10.1

If those functions are wrapped by h5py, the import order problem might be solved in a clean manner.

**Comment by aragilar** [comment]
It makes sense to wrap H5PLappend in h5py (falling back to appending to `HDF5_PLUGIN_PATH` for pre 1.8.19 releases). h5py should also add some hooks in https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py#L53 and https://github.com/h5py/h5py/blob/master/h5py/_hl/filters.py to allow filters to provide a more usable interface than passing in filter numbers.

**Comment by vasole** [comment]
I got the confirmation from the HDF5 Group about those functions being present in 1.10.1
They are going to add them to the documentation.

**Comment by vasole** [comment]
https://github.com/h5py/h5py/pull/1166 implements all the required functionality

**Comment by vasole** [comment]
@aragilar 

It is a work in progress, but the current master should allow generation of the LZ4, bishuffle+LZ4 and Blosc plugins on Windows, Mac and Linux. Furthermore, compression and decompression should work.

**Comment by aragilar** [comment]
Nice! Did you want to make an announcement on the h5py mailing list asking for testers?

**Comment by t20100** [comment]
Definitely, but I'd like to build some wheels and push a pre-release on pypi first, so the release process gets tested at the same time.

**Comment by vasole** [comment]
I think this can be closed with the pre-release and the announcement in the h5py mailing list.
