### ISSUE TITLE
Add H5Z-SPERR to the collection?

### ISSUE THREAD

**Issue by shaomeng** [silx-kit/hdf5plugin#302]
Hello HDF5Plugin Developers,

[NCAR](https://en.wikipedia.org/wiki/National_Center_for_Atmospheric_Research) has an increased interest in `hdf5plugin` because it provides an easy approach to integrate lossy compression in Python-based workflows. However, `hdf5plugin` currently misses an important algorithm, namely [SPERR](https://github.com/NCAR/SPERR). I have recently developed a HDF5 plugin for `SPERR` ([H5Z-SPERR](https://github.com/NCAR/H5Z-SPERR/tree/v0.1.0)), and I wonder if it's possible to add `H5Z-SPERR` to `hdf5plugin`? I have very little knowledge in Python, but I can provide help in any other way w.r.t. the algorithm to make this integration happen.

Thanks,
Sam

**Comment by t20100** [comment]
Hi,

Thanks for the interest in `hdf5plugin`.

Yes, since SPERR is an official HDF5 plugin, we can consider it for addition in this project.
There is some [guidelines](https://github.com/silx-kit/hdf5plugin/blob/main/doc/contribute.rst#guidelines-to-add-a-compression-filter) that gives an idea of the process.

I had a first look and have a first few questions:
- The first constraint is about dependencies since we embed all the source code to generate the HDF5 filters. It seems only [SPERR](https://github.com/NCAR/SPERR) is needed, am I right?
- Then, as hdf5plugin is currently implemented, the build is done with Python's `setuptools`. This basically means that the cmake config need to be rewritten for `setuptools`. SPERR is relying on OpenMP and can be compiled with C++11 (or C++20 which we do not probe yet + would not be used for Python wheels). Did I miss something (e.g., SIMD) ?
- The [H5Z_SPERR_make_cd_values](https://github.com/NCAR/H5Z-SPERR/blob/4ae7bed2f94e943f5961f7d8196b1749a8444c00/include/h5z-sperr.h#L21) function would also need to be converted to Python to provide a class to easily configure the filter. BTW, is the current implementation resilient to different endianness?

**Comment by shaomeng** [comment]
Hi Thomas,

Thanks for the encouraging news. I did take a look at the guidelines, and that's why I backed off implementing by myself: I really don't understand a lot of the python stuff. I have answers to your questions below:

>     * The first constraint is about dependencies since we embed all the source code to generate the HDF5 filters. It seems only [SPERR](https://github.com/NCAR/SPERR) is needed, am I right?
It's correct. SPERR only needs a C++ compiler to build a library (no CLI utilities). 
> 
>     * Then, as hdf5plugin is currently implemented, the build is done with Python's `setuptools`. This basically means that the cmake config need to be rewritten for `setuptools`. SPERR is relying on OpenMP and can be compiled with C++11 (or C++20 which we do not probe yet + would not be used for Python wheels). Did I miss something (e.g., SIMD) ?
- `setuptools`: I can work on the SPERR CMake so that it's easy to cooperate with `setuptools`. Do you know if there's a good documentation on what's exactly required? 
-  C++ standards: What's the latest C++ standard that Python wheels support? I can use macros in SPERR to replace C++ code beyond Python wheels can support.
- OpenMP: In fact, it's best to disable OpenMP in SPERR when used as a HDF5 filter, so there's not a problem here.
> 
>     * The [H5Z_SPERR_make_cd_values](https://github.com/NCAR/H5Z-SPERR/blob/4ae7bed2f94e943f5961f7d8196b1749a8444c00/include/h5z-sperr.h#L21) function would also need to be converted to Python to provide a class to easily configure the filter. BTW, is the current implementation resilient to different endianness?
Well, I didn't really take endianness into consideration when writing the code, but through my discussion with H5Z-ZFP developers, I *think* it might be. The truth is, it's extremely difficult to locate a big endian machine today, not only for real workload, but also for testing. I consider that the endianness doesn't matter that much.

**Comment by t20100** [comment]
Thanks for your answer!

> setuptools: I can work on the SPERR CMake so that it's easy to cooperate with setuptools. Do you know if there's a good documentation on what's exactly required?

Sorry, I wasn't clear. Ideally we would call cmake to build the plugins, but as it is now, we need to "duplicate" the build configuration as a Python `setuptools` one: basically setting the compilation flags and list of files to build. So the simpler the better ;)

> C++ standards: What's the latest C++ standard that Python wheels support? I can use macros in SPERR to replace C++ code beyond Python wheels can support.

We currently provide [manylinux2014](https://peps.python.org/pep-0599/) wheel. Those are built with GCC 10 (see https://github.com/pypa/manylinux?tab=readme-ov-file#manylinux2014-centos-7-based) and certainly supports C++14. According to https://gcc.gnu.org/projects/cxx-status.html#cxx20: "C++20 features are available since GCC 8", so it should be fine.

> OpenMP: In fact, it's best to disable OpenMP in SPERR when used as a HDF5 filter, so there's not a problem here.

OK, we don't build wheels with OpenMP support, but we can enable it when building from source (it is already done for other filters).

Let's keep the endianness check for later.

I can give it a try when I have a bit of free time, since there is no dependencies, it should be easy to make a first integration.

**Comment by shaomeng** [comment]
> 
> Sorry, I wasn't clear. Ideally we would call cmake to build the plugins, but as it is now, we need to "duplicate" the build configuration as a Python `setuptools` one: basically setting the compilation flags and list of files to build. So the simpler the better ;)

Sounds cool. I just want to point out a compilation flag, `USE_VANILLA_CONFIG`, that can be passed in, so that the code won't try to include a cmake-generated file: `SperrConfig.h`. See [here](https://github.com/NCAR/SPERR/blob/59aa63c3d8eca9fdaaf46ba954d3c2bf675a25be/include/sperr_helper.h#L19-L21).
> 

> We currently provide [manylinux2014](https://peps.python.org/pep-0599/) wheel. Those are built with GCC 10 (see https://github.com/pypa/manylinux?tab=readme-ov-file#manylinux2014-centos-7-based) and certainly supports C++14. According to https://gcc.gnu.org/projects/cxx-status.html#cxx20: "C++20 features are available since GCC 8", so it should be fine.

Ok, I think the best approach is to give it a test as it is right now, and I can certainly address any issues complained by the compiler.
> 
> OK, we don't build wheels with OpenMP support, but we can enable it when building from source (it is already done for other filters).

Let's not enable it from source too; there just won't be any benefit as a plugin. SPERR benefits from OpenMP when itself handles chunking schemes; it uses one OpenMP thread to compress on one chunk. As a plugin, chunking is already handled by HDF5, so there's just no benefit to enable OpenMP!
> 
> I can give it a try when I have a bit of free time, since there is no dependencies, it should be easy to make a first integration.

Thanks Thomas, please let me know if I could help with the C/C++ side of things!
