### ISSUE TITLE
Timing for 2.0 release?

### ISSUE THREAD

**Issue by rlizzo** [silx-kit/hdf5plugin#44]
Hi team, just wondering what the timing for the v2.0 release will be? I saw the pre-release a few days, ago, and got very excited about being able to include it in [the project I maintain](https://github.com/tensorwerk/hangar-py) in our upcoming 0.4 release (which I'd like to get out in the next two weeks or so).

If there's anything you could use some help on, I'd be happy to contribute a PR or two to help speed along the process. Just let me know!

Best,
Rick

**Comment by vasole** [comment]
We just wanted feedback from the community. I do not think we have any showstopper to make a release.

**Comment by rlizzo** [comment]
Ahh excellent! Thanks for the quick reply!

I've had a remarkable amount of success with the pre-release. Everything seems to go as expected.

A few notes about the documentation though:
- state which versions of python this is compatible with (is python 3.8 supported? I haven't tried it myself yet)
- state that the project is available on linux, macos, and windows (windows support is something that is missing from the `blosc-hdf5-plugin` package on `conda-forge`.  

In addition, it's not explained why it states in the readme 

> "Whenever possible, HDF5 compression filter plugins are best installed system-wide or through Anaconda (blosc-hdf5-plugin, hdf5-lz4)."

I'm actually not sure of that myself? 

Finally, I know there was an issue about this awhile ago in #17, but is there any plan to add this to the `conda-forge` anaconda channel?  I only have to say that this would be beneficial for projects which desire to keep their depedencies on `pypi` and `conda-forge` in sync. I've got some experience packaging for both independent `anaconda` channels as well as `conda-forge`, and would be happy to help put together a `conda-forge feedstock` with the team after 2.0 is finally released!

**Comment by rlizzo** [comment]
Also, just worth saying thank you for all your hard work on this! It's much appreciated by a fellow open-source project maintainer! This is a phenomenal "quality of life" project which will improve my library and users life drastically!

**Comment by vasole** [comment]
Python 3.8 is supported. The only compiled code are the plugins themselves.

Using the plugins as provided by the system maintainers make sure they were compiled using the same settings used to compile the HDF5 library itself. When one compiles HDF5, there is a file named H5pubconf.h to be used when compiling against the library.

We supply the H5pubconf.h file with the sources of hdf5plugin in order to make sure it can be built. 

Let me illustrate our caveats. On Anaconda, in order to be 100% sure one would have to rely on the H5pubconf.h generated when compiling HDF5 on Anaconda.

May be we are too cautious but until the module is more heavily tested we prefer to say that.

Previous versions of hdf5plugin were working everywhere with just compression disabled on linux and mac and they had no interference with anything but we prefer to have the package more heavily tested prior to claim it works everywhere.

**Comment by t20100** [comment]
Thanks for the feedback!
I'll update the documentation accordingly.

We're about to make a release (early next week).

The possible caveat regarding compatibility is that we include the "config" header of HDF5 in the source in order to allow stand-alone build, but that can be mitigated with an option to override it.

Regarding conda, to me `hdf5plugin` was meant to work where others don't, but I fully understand you want to keep the same dependencies no matter the installation environment.

**Comment by vasole** [comment]
@t20100 

Instead of adding an option to just overwrite the H5pubconf.h file we could provide an option to provide the path to the installed HDF5 library itself so that everything is taken from the installed system.

**Comment by t20100** [comment]
@vasole, yes this is what I want to do.

**Comment by rlizzo** [comment]
Hi @vasole thanks so much for the detailed reply. This has been very helpful. Just saw the 2.0.0 release! Congratulations on the big milestone, and know you have (atleat) one very happy user over here! 

Feel free to close this issue at your convenience. 

Have a great week!
Rick

**Comment by t20100** [comment]
Thanks for the positive feedback!

BTW, wheels are now available on pypi.
