### ISSUE TITLE
Add Zstandard HDF5 plugin

### ISSUE THREAD

**Issue by lilastic** [silx-kit/hdf5plugin#93]
Would it be possible to add Zstandard (https://facebook.github.io/zstd/) in the form of an HDF5 plugin into your repository? An already possible integration can be found here: https://github.com/aparamon/HDF5Plugin-Zstandard. Thanks and keep up the good work! :)

**Comment by t20100** [comment]
Zstd is already available as part of the Blosc filter, see https://github.com/silx-kit/hdf5plugin#blosc-cname-lz4-clevel-5-shuffle-shuffle

But yes, this filter could be added.
Since Zstd is already used by the blosc filter, the sources are already included, so I don't see major issue in adding it here.

If you feel like making a Pull Request for it, you can check https://github.com/silx-kit/hdf5plugin/blob/master/doc/contribute.rst

**Comment by lilastic** [comment]
Thanks for the info @t20100!

Not sure if I'm able to do it as I'm not used with the process of building filters for HDF5. Would you mind to do it? Thanks!

**Comment by t20100** [comment]
I don't have time for it right now, but we'll definitely add Zstd to the filter zoo.

In the meantime, if you want to give a try we can provide support.

**Comment by vasole** [comment]
@lilastic 

#106 adds support for Zstandard but we lack any reference data for testing.

Do you have any data already using that compression filter?
